### ISSUE TITLE
环境配置请教

### ISSUE THREAD

**Issue by jwx15** [AlirezaOmrani95/HDR-VAM#2]
您好，我想请问跑这个模型需要的环境配置。

**Comment by AlirezaOmrani95** [comment]
Hello, the requirements file has been added.

**Comment by jwx15** [comment]
> 您好，需求文件已添加。

谢谢，还有个问题就是下载数据集的链接是不有问题啊，不知道该怎么下载

**Comment by jwx15** [comment]
think you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlirezaOmrani95/HDR-VAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlirezaOmrani95/HDR-VAM] 环境配置请教 (Issue #2)





 
Hello, the requirements file has been added.

**Comment by AlirezaOmrani95** [comment]
Please register on the following website to receive the dataset.

https://competitions.codalab.org/competitions/28162
